version: "3"

services:
  mongo:
    restart: always
    image: "mongo:3.6.3"
  app:
    build: .
    restart: always
    environment:
      SERVER_PORT: "8080"
      MONGO_HOST: "mongo:27017"
      ES_HOST: "es:9200"
      REDIS_HOST: "redis:6379"
      SAVE_DIR: ../../
    env_file: .env.sample
    depends_on:
      - mongo
      - es
      - redis
  es:
    build: es
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  redis:
    restart: always
    image: "redis:5.0.4"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
