version: "3"

services:
  mongo:
    restart: always
    image: "mongo:3.6.3"
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    restart: always
    environment:
      SERVER_PORT: "8080"
      MONGO_HOST: "mongo:27017"
      ES_HOST: "es:9200"
      REDIS_HOST: "redis:6379"
      SAVE_DIR: ../../
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - es
      - redis
    volumes:
      - ./data/app/logs:/home/app/.anontown/logs
      - ./data/app/data:/home/app/.anontown/data
  es:
    build: es
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
  redis:
    restart: always
    image: "redis:5.0.4"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
