apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: es
      context: es
    - image: server
      context: server
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
          - "packages/*"
    - image: client
      context: client
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
          - "packages/*"
    - image: doc
      context: doc
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
          - "src/*"
    - image: camo
      context: camo
portForward:
  - resourceType: deployment
    resourceName: camo
    port: 4181
  - resourceType: deployment
    resourceName: client
    port: 3000
  - resourceType: deployment
    resourceName: doc
    port: 4928
  - resourceType: deployment
    resourceName: server
    port: 8080
