apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: es
      context: es
    - image: server
      context: server
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: "."
    - image: client
      context: client
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: "."
          - src: "**/*.tsx"
            dest: "."
          - src: "**/*.scss"
            dest: "."
    - image: doc
      context: doc
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: "**/*.md"
            dest: "."
    - image: camo
      context: camo
deploy:
  kubectl:
    manifests:
      - k8s/*
      - env/*
portForward:
  - resourceType: service
    resourceName: camo
    port: 4181
  - resourceType: service
    resourceName: client
    port: 3000
  - resourceType: service
    resourceName: doc
    port: 4928
  - resourceType: service
    resourceName: server
    port: 8080
