version: 2
jobs:
  server:
    working_directory: ~/anontown
    docker:
      - image: node:10.15.3
        environment:
          SALT_PASS: aaa
          SALT_HASH: bbb
          SALT_TOKEN: ccc
          SALT_TOKEN_REQ: ddd
          RECAPTCHA_SITE_KET: xxxxxxxxxxxx
          RECAPTCHA_SECRET_KET: xxxxxxxxxxx
          SERVER_PORT: 8080
          DB_URL: mongodb://localhost:27017/anontown
          ES_HOST: localhost:9200
          SAVE_DIR: ../../data/app/
          REDIS_URL: redis://localhost:6379/0
          AT_MODE: TEST
          DOCKERIZE_VERSION: v0.6.1
          NODE_OPTIONS: --max_old_space_size=700
      - image: mongo:3.6.3
      - image: anontown/elasticsearch:5.6.16-1
        environment:
          http.host: '0.0.0.0'
          http.port: 9200
          xpack.security.enabled: false
          ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      - image: redis:5.0.4
    steps:
      - checkout
      - run:
          name: dockerize
          command: |
            apt update
            apt install -y wget
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      - run:
          name: server build and test
          command: |
            npm i --no-progress
            npx lerna bootstrap
            npx lerna exec --scope @anontown/server -- npm run build
            mkdir data
            mkdir data/app
            dockerize -wait tcp://$ES_HOST
            npx lerna exec --scope @anontown/server -- npm run test:io
  client:
    working_directory: ~/anontown
    docker:
      - image: node:10.15.3
        environment:
          NODE_OPTIONS: --max_old_space_size=2048
    steps:
      - checkout
      - run:
          name: client build
          command: |
            npm i
            npx lerna bootstrap
            npx lerna exec --scope @anontown/client -- npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - server
      - client