apiVersion: v1
kind: Service
metadata:
  name: camo
spec:
  ports:
    - port: 4181
  selector:
    app: camo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camo
spec:
  selector:
    matchLabels:
      app: camo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: camo
    spec:
      containers:
        - image: anontown-camo
          name: camo
          env:
            - name: PORT
              value: "4181"
            - name: CAMO_KEY
              valueFrom:
                configMapKeyRef:
                  name: common
                  key: CAMO_KEY
          ports:
            - containerPort: 4181
