apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
    - port: 3000
  selector:
    app: client
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: client
          name: client
          env:
            - name: PORT
              value: "3000"
            - name: RECAPTCHA_SITE_KET
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RECAPTCHA_SITE_KET
            - name: CLIENT_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: client-url
                  key: CLIENT_ORIGIN
            - name: CAMO_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: client-url
                  key: CAMO_ORIGIN
            - name: CAMO_KEY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CAMO_KEY
            - name: API_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: client-url
                  key: API_ORIGIN
            - name: SOCKET_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: client-url
                  key: SOCKET_ORIGIN
            - name: IMGUR_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: IMGUR_CLIENT_ID
            - name: GA
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: GA
          ports:
            - containerPort: 3000
