apiVersion: v1
kind: Service
metadata:
  name: doc
spec:
  ports:
    - port: 4928
      targetPort: 80
  selector:
    app: doc
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc
spec:
  selector:
    matchLabels:
      app: doc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: doc
    spec:
      containers:
        - image: doc
          name: doc
          ports:
            - containerPort: 80
