apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  ports:
    - port: 9200
  selector:
    app: es
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - image: anontown-es
          name: es
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: es-volume
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-volume
          hostPath:
            path: /data/anontown/es
            type: DirectoryOrCreate
