apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  ports:
    - port: 9200
  selector:
    app: es
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  labels:
    app: es
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/anontown/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
spec:
  selector:
    matchLabels:
      app: es
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - image: es
          name: es
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: es-volume
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-volume
          persistentVolumeClaim:
            claimName: es-pvc
