version: "3.4"
services:
  app:
    build: .
    environment:
      SERVER_PORT: "8080"
      MONGO_HOST: mongo:27017
      ES_HOST: es:9200
      REDIS_HOST: redis:6379
      SALT_PASS: aaa
      SALT_HASH: bbb
      SALT_TOKEN: ccc
      SALT_TOKEN_REQ: ddd
      RECAPTCHA_SITE_KET: xxxxxxxxxxxx
      RECAPTCHA_SECRET_KET: xxxxxxxxxxx
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - es
      - redis
  mongo:
    restart: always
    build: ../mongo
  es:
    build: ../es
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  redis:
    build: ../redis
