version: "3.4"
services:
  app:
    build: .
    environment:
      SERVER_PORT: "8080"
      REDIS_HOST: redis:6379
      SALT_PASS: aaa
      SALT_HASH: bbb
      SALT_TOKEN: ccc
      SALT_TOKEN_REQ: ddd
      RECAPTCHA_SITE_KET: xxxxxxxxxxxx
      RECAPTCHA_SECRET_KET: xxxxxxxxxxx
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
  db:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  redis:
    build: ../redis

