name: ci

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: docker-compose -f docker-compose-test.yml build
      - name: lint-client
        run: make lint.client
      - name: lint-server
        run: make lint.server
      - name: test-server
        run: make test.server
  build-and-push:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/topic/')
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $PERSONAL_TOKEN
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin
      - name: build-and-push
        run: skaffold build -p prod
        env:
          SKAFFOLD_DEFAULT_REPO: docker.pkg.github.com/${{ github.repository }}
