name: ci

on: [push]

jobs:
  build-and-static-check-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build image
        run: docker build -t server .
        working-directory: server
      - name: lint
        run: docker run --rm server ./bin/lint.sh
        working-directory: server
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run sysctl
        run: sudo sysctl -w vm.max_map_count=262144
      - name: test
        run: make test
        working-directory: server
  build-and-static-check-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build image
        run: docker build -t client .
        working-directory: client
      - name: lint
        run: docker run --rm client ./bin/lint.sh
        working-directory: client
  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - build-and-static-check-server
      - build-and-test-server
      - build-and-static-check-client
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $PERSONAL_TOKEN
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin
      - name: install node
        uses: actions/setup-node@v1
      - name: build-and-push
        run: TAG_SUFFIX=$(node gen-tag-suffix.js) skaffold build -p prod
        env:
          SKAFFOLD_DEFAULT_REPO: docker.pkg.github.com/${{ github.repository }}
          REF: ${{ github.ref }}
