name: CI

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: DC_ENV=test python3 docker-compose.py | docker-compose -f - build
      - name: test
        run: DC_ENV=test python3 docker-compose.py | docker-compose -f - run --rm app npx lerna run test:io --scope @anontown/server
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          version: 10
      - name: install
        run: |
          npm i
          npx lerna bootstrap
      - name: lint
        run: |
          npx lerna run lint --scope @anontown/client
          npx lerna run lint --scope @anontown/server
      - name: build
        run: npx lerna run build --scope @anontown/client --include-filtered-dependencies
