name: main

on: [push]

env:
  APP_IMAGE_TAG: docker.pkg.github.com/${{ github.repository }}/app:${{ github.sha }}
  ES_IMAGE_TAG: docker.pkg.github.com/${{ github.repository }}/es:${{ github.sha }}

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dcdy
        run: |
          mkdir -p ~/.local/bin
          curl -sSf https://raw.githubusercontent.com/kgtkr/dcdy/master/install.sh | sh
          echo ::add-path::$HOME/.local/bin
      - name: build
        run: DCDY_MODE=test dcdy build
      - name: lint
        run: DCDY_MODE=test dcdy run --rm app npx lerna run lint --scope @anontown/server
      - name: test
        run: DCDY_MODE=test dcdy run --rm app npx lerna run test:io --scope @anontown/server
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          version: 10
      - name: install
        run: |
          npm i
          npx lerna bootstrap
      - name: lint
        run: |
          npx lerna run lint --scope @anontown/client
      - name: build
        run: npx lerna run build --scope @anontown/client --include-filtered-dependencies
  docker-build-and-push:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/topic/')
    runs-on: ubuntu-latest
    needs: [server]
    steps:
      - uses: actions/checkout@v1
      - name: login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $PERSONAL_TOKEN
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: build
        run: |
          docker build -t $APP_IMAGE_TAG .
          docker build -t $ES_IMAGE_TAG es
      - name: push
        run: |
          docker push $APP_IMAGE_TAG
          docker push $ES_IMAGE_TAG
  release-commit:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: build
        run: |
          mkdir release
          DCDY_MODE=prod DCDY_APP_IMAGE=$APP_IMAGE_TAG DCDY_ES_IMAGE=$ES_IMAGE_TAG ./docker-compose.dy > release/docker-compose.yml
          cp bin/manager.sh release/manager.sh
          chmod +x release/manager.sh
          cp README.md release
          cp .env.sample release
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: release
          PUBLISH_DIR: ./release
