name: main

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dcdy
        run: |
          mkdir -p ~/.local/bin
          curl -sSf https://raw.githubusercontent.com/kgtkr/dcdy/master/install.sh | sh
          echo ::add-path::$HOME/.local/bin
      - name: build
        run: DCDY_MODE=test dcdy build
      - name: test
        run: DCDY_MODE=test dcdy run --rm app npx lerna run test:io --scope @anontown/server
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          version: 10
      - name: install
        run: |
          npm i
          npx lerna bootstrap
      - name: lint
        run: |
          npx lerna run lint --scope @anontown/client
          npx lerna run lint --scope @anontown/server
      - name: build
        run: npx lerna run build --scope @anontown/client --include-filtered-dependencies
