name: server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: build
      run: python3 docker-compose.py test | docker-compose -f - build
    - name: test
      run: python3 docker-compose.py test | docker-compose -f - run --rm app npx lerna run test:io --scope @anontown/server
